global:
  containerRegistry: ggakg
# Common Labels
labels:
  app: "loan"
  group: "health"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "loan"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "public-loan"
    image:
      repository: "dbmigrate"

# Container Configs
image:
  repository: "loan"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/loan/health"
  readinessProbePath: "/loan/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
memory_limits: "1Gi"
java-args: "-Dspring.profiles.active=monitoring"
persist-yml-path: "file:///work-dir/digit-configs.git/egov-persister/loan-persister.yml"
indexer-yml-path: "file:///work-dir/digit-configs.git/egov-indexer/loan-indexer.yml"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "/egov-mdms-service/v1/_search"
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: SPRING_REDIS_HOST
    value: "redis.backbone.svc.cluster.local"
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: SPRING_CACHE_TYPE
    value: "redis"
  - name: SPRING_CACHE_REDIS_TIME-TO-LIVE
    value: "60"
  - name: SPRING_CACHE_AUTOEXPIRY
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  