version: v2.8
modules:
    - name: backbone
      services:
        - zookeeper-v2
        - kafka-v2
        - kafka-connect
        - kafka-connect-restart-tasks
        - elasticsearch-data-v1
        - elasticsearch-master-v1
        - kibana-v1
    - name: authn-authz
      services:
        - redis
        - nginx-ingress
        - cert-manager
        - zuul:v1.3.1-96b24b0d72-39     
    - name: core
      dependencies:
        - "backbone"
        - "authn-authz"    
      services:
        - egovio/egov-accesscontrol:v1.1.4-6cfa52c1f9-1
        - egovio/egov-enc-service:v1.1.4-6cfa52c1f9-1
        - egovio/xstate-chatbot:v1.1.1-96b24b0d72-1
        - egovio/egov-searcher:v1.1.6-6cfa52c1f9-1
        - egovio/egov-pg-service:v1.2.4-6cfa52c1f9-1
        - egovio/egov-filestore:v1.2.5-6cfa52c1f9-1
        - egovio/zuul:v1.3.2-6cfa52c1f9-1
        - egovio/egov-notification-mail:v1.1.3-6cfa52c1f9-1
        - egovio/egov-notification-sms:v1.1.4-6cfa52c1f9-1
        - egovio/egov-localization:v1.1.4-6cfa52c1f9-1
        - egovio/egov-persister:v1.1.5-6cfa52c1f9-2
        - egovio/egov-idgen:v1.2.4-6cfa52c1f9-1
        - egovio/egov-user:v1.3.0-6cfa52c1f9-2
        - egovio/egov-user-chatbot:v1.3.0-6cfa52c1f9-1
        - egovio/egov-mdms-service:v1.3.3-6cfa52c1f9-1
        - egovio/egov-url-shortening:v1.1.3-6cfa52c1f9-1
        - egovio/egov-indexer:v1.1.8-6cfa52c1f9-1
        - egovio/report:v1.3.5-6cfa52c1f9-1
        - egovio/egov-workflow-v2:v1.2.2-6cfa52c1f9-1
        - egovio/pdf-service:v1.2.1-6cfa52c1f9-1
        - egovio/chatbot:v1.1.7-6cfa52c1f9-1
        - egovio/egov-location:v1.1.5-6cfa52c1f9-1
        - egovio/egov-otp:v1.2.3-6cfa52c1f9-1
        - egovio/user-otp:v1.1.6-6cfa52c1f9-2
        - egovio/nlp-engine:v1.0.0-fbea6fba-21
        - egovio/egov-document-uploader:v1.1.1-6cfa52c1f9-4
        - egovio/national-dashboard-ingest:v1.0.1-6cfa52c1f9-1
        - egovio/national-dashboard-kafka-pipeline:v1.0.1-6cfa52c1f9-1
        - egovio/egov-survey-services:v0.0.1-a9d54c2543-25
        - egovio/playground:1.0

    - name: business
      dependencies:
        - "core"
      services:
        - egovio/egov-hrms:v1.2.5-d93a120c25-2
    - name: "frontend"             
      dependencies:
        - "business"
      services:
        - egovio/citizen:v1.9.0-98adbd4488-17
        - egovio/employee:v1.9.0-98adbd4488-17
        - egovio/digit-ui:v1.6.0-98adbd4488-74
    - name: m_pgr             #PGR
      dependencies:
        - "core"
        - "business"
      services:
        - egovio/pgr-services:v1.1.7-3d7f744977-1
        - egovio/rainmaker-pgr:v1.1.4-32caf0d992-4
    - name: m_dss   #dss
      dependencies:        
          - "frontend"
          - "core"
          - "business"
      services:
        - egovio/dashboard-analytics:v1.1.8-d93a120c25-2
        - egovio/dashboard-ingest:v1.1.4-d93a120c25-2  
        - egovio/dss-dashboard:v1.9.0-98adbd4488-1
